name: dubuc_app
description: Application de gestion des jobs Dubuc & CO
publish_to: 'none'
version: 1.1.0+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.1.0
  mobile_scanner: ^3.5.5
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  flutter_local_notifications: ^16.3.2
  flutter_background_service: ^5.0.5
  flutter_background_service_android: ^6.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
